FROM i386/ubuntu:latest

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y mingw-w64 zip upx libgtk-3-dev wget git

RUN wget -O nim.tar.xz https://nim-lang.org/download/nim-1.6.2-linux_x32.tar.xz && tar xf nim.tar.xz && rm nim.tar.xz

ENV PATH="/nim-1.6.2/bin:${PATH}"

WORKDIR /app

CMD nimble build_linux_i386
